### ISSUE TITLE
Question: Padding of PREGSTAT

### ISSUE THREAD

**Issue by mboyas-mitre** [verbal-autopsy-software/InterVA4#2]
https://github.com/verbal-autopsy-software/InterVA4/blob/792fd94fcad1f143f55865e580a4ea0bc233e5bb/InterVA4_1.7/R/InterVA.R#L95

Why is this padding of the string necessary?  Could PREGSTAT be more than five characters (either legitimately or illegitimately)? If so, then we might be altering true information that could be useful.

**Comment by richardli** [comment]
All possible PREGSTAT are less than 5 characters. The particular paddling is to be consistent with InterVA-4 software output, so that we have the same number of spaces when it comes to text alignment.
