### ISSUE TITLE
Question: Conditional probability labels

### ISSUE THREAD

**Issue by mboyas-mitre** [verbal-autopsy-software/InterVA4#6]
https://github.com/verbal-autopsy-software/InterVA4/blob/792fd94fcad1f143f55865e580a4ea0bc233e5bb/InterVA4_1.7/R/InterVA.R#L217-L234

Do these conditional probability values ever need to be variables / would it be useful to make them be easily editable for future work?

**Comment by richardli** [comment]
the letter values can be directly extracted from InterVA-4 and InterVA-5 software, so it's easier to update whenever InterVA software changes them. Also they are useful in InSilicoVA algorithm too, so it's easier to maintain across the various R packages too.
