### ISSUE TITLE
Question: Ask/Don't Ask Repetitions

### ISSUE THREAD

**Issue by mboyas-mitre** [verbal-autopsy-software/InterVA4#8]
We follow what you are doing here, but why is this check only being repeated twice?  Is it possible that there still could be issues after the second check has been completed?

https://github.com/verbal-autopsy-software/InterVA4/blob/792fd94fcad1f143f55865e580a4ea0bc233e5bb/InterVA4_1.7/R/InterVA.R#L322-L326

**Comment by richardli** [comment]
Yes, again it's the logic of the InterVA-4 software.
